version: '3.8'

services:
  backend-app:
    image: backend-app:3.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_CODEANYTHING_URL: jdbc:mysql://db:3306/codeanything
      SPRING_DATASOURCE_ABOUTME_URL: jdbc:mysql://db:3306/aboutme
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
  #  depends_on:
  #    - db